/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "whiteboard.h"
#include <stdio.h>
#include <stdlib.h>
#include <rpc/pmap_clnt.h>
#include <string.h>
#include <memory.h>
#include <sys/socket.h>
#include <netinet/in.h>

#ifndef SIG_PF
#define SIG_PF void(*)(int)
#endif

static void
whiteboard_prog_1(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		quadro new_quadro_1_arg;
		quadro signin_quadro_1_arg;
		quadro erase_user_1_arg;
	} argument;
	char *result;
	xdrproc_t _xdr_argument, _xdr_result;
	char *(*local)(char *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply (transp, (xdrproc_t) xdr_void, (char *)NULL);
		return;

	case NEW_QUADRO:
		_xdr_argument = (xdrproc_t) xdr_quadro;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) new_quadro_1_svc;
		break;

	case SIGNIN_QUADRO:
		_xdr_argument = (xdrproc_t) xdr_quadro;
		_xdr_result = (xdrproc_t) xdr_msg;
		local = (char *(*)(char *, struct svc_req *)) signin_quadro_1_svc;
		break;

	case INICIALIZA:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_void;
		local = (char *(*)(char *, struct svc_req *)) inicializa_1_svc;
		break;

	case LISTAR_QUADROS:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_history;
		local = (char *(*)(char *, struct svc_req *)) listar_quadros_1_svc;
		break;

	case ERASE_USER:
		_xdr_argument = (xdrproc_t) xdr_quadro;
		_xdr_result = (xdrproc_t) xdr_msg;
		local = (char *(*)(char *, struct svc_req *)) erase_user_1_svc;
		break;

	default:
		svcerr_noproc (transp);
		return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return;
	}
	result = (*local)((char *)&argument, rqstp);
	if (result != NULL && !svc_sendreply(transp, (xdrproc_t) _xdr_result, result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		fprintf (stderr, "%s", "unable to free arguments");
		exit (1);
	}
	return;
}

static void
whiteboard_prog_2(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		int fill;
	} argument;
	char *result;
	xdrproc_t _xdr_argument, _xdr_result;
	char *(*local)(char *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply (transp, (xdrproc_t) xdr_void, (char *)NULL);
		return;

	case WBADMIN:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_history;
		local = (char *(*)(char *, struct svc_req *)) wbadmin_2_svc;
		break;

	default:
		svcerr_noproc (transp);
		return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return;
	}
	result = (*local)((char *)&argument, rqstp);
	if (result != NULL && !svc_sendreply(transp, (xdrproc_t) _xdr_result, result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		fprintf (stderr, "%s", "unable to free arguments");
		exit (1);
	}
	return;
}

int
main (int argc, char **argv)
{
	register SVCXPRT *transp;

	pmap_unset (WHITEBOARD_PROG, WHITEBOARD_VERSION);
	pmap_unset (WHITEBOARD_PROG, WBADMIN_VERSION);

	transp = svcudp_create(RPC_ANYSOCK);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create udp service.");
		exit(1);
	}
	if (!svc_register(transp, WHITEBOARD_PROG, WHITEBOARD_VERSION, whiteboard_prog_1, IPPROTO_UDP)) {
		fprintf (stderr, "%s", "unable to register (WHITEBOARD_PROG, WHITEBOARD_VERSION, udp).");
		exit(1);
	}
	if (!svc_register(transp, WHITEBOARD_PROG, WBADMIN_VERSION, whiteboard_prog_2, IPPROTO_UDP)) {
		fprintf (stderr, "%s", "unable to register (WHITEBOARD_PROG, WBADMIN_VERSION, udp).");
		exit(1);
	}

	transp = svctcp_create(RPC_ANYSOCK, 0, 0);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create tcp service.");
		exit(1);
	}
	if (!svc_register(transp, WHITEBOARD_PROG, WHITEBOARD_VERSION, whiteboard_prog_1, IPPROTO_TCP)) {
		fprintf (stderr, "%s", "unable to register (WHITEBOARD_PROG, WHITEBOARD_VERSION, tcp).");
		exit(1);
	}
	if (!svc_register(transp, WHITEBOARD_PROG, WBADMIN_VERSION, whiteboard_prog_2, IPPROTO_TCP)) {
		fprintf (stderr, "%s", "unable to register (WHITEBOARD_PROG, WBADMIN_VERSION, tcp).");
		exit(1);
	}

	svc_run ();
	fprintf (stderr, "%s", "svc_run returned");
	exit (1);
	/* NOTREACHED */
}
