/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "whiteboard.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

int *
new_quadro_1(quadro *argp, CLIENT *clnt)
{
	static int clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, NEW_QUADRO,
		(xdrproc_t) xdr_quadro, (caddr_t) argp,
		(xdrproc_t) xdr_int, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

msg *
signin_quadro_1(quadro *argp, CLIENT *clnt)
{
	static msg clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, SIGNIN_QUADRO,
		(xdrproc_t) xdr_quadro, (caddr_t) argp,
		(xdrproc_t) xdr_msg, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

void *
inicializa_1(void *argp, CLIENT *clnt)
{
	static char clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, INICIALIZA,
		(xdrproc_t) xdr_void, (caddr_t) argp,
		(xdrproc_t) xdr_void, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return ((void *)&clnt_res);
}

history *
listar_quadros_1(void *argp, CLIENT *clnt)
{
	static history clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, LISTAR_QUADROS,
		(xdrproc_t) xdr_void, (caddr_t) argp,
		(xdrproc_t) xdr_history, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

msg *
erase_user_1(quadro *argp, CLIENT *clnt)
{
	static msg clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, ERASE_USER,
		(xdrproc_t) xdr_quadro, (caddr_t) argp,
		(xdrproc_t) xdr_msg, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

history *
wbadmin_2(void *argp, CLIENT *clnt)
{
	static history clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, WBADMIN,
		(xdrproc_t) xdr_void, (caddr_t) argp,
		(xdrproc_t) xdr_history, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}
